In [1]:
import pandas as pd

df = pd.read_csv('SVM_Dataset1.csv', index_col = 0)

In [2]:
df

X1        X2  y
0  2.947814  6.626878  1
1  2.530388  7.785050  1
2  3.566991  5.651046  1
3  3.156983  5.467077  1
4  2.582346  4.457777 -1
5  2.155826  6.222343 -1
6  3.273418  3.520687 -1

In [6]:
import numpy as np
X1 = df['X1']
X2 = df['X2']
X_train = np.array(list(zip(X1,X2)))
X_train

array([[2.947814, 6.626878],
       [2.530388, 7.78505 ],
       [3.566991, 5.651046],
       [3.156983, 5.467077],
       [2.582346, 4.457777],
       [2.155826, 6.222343],
       [3.273418, 3.520687]])

In [8]:
y_train = df['y'].values

print(y_train)

[ 1  1  1  1 -1 -1 -1]


In [9]:
color_lst = []
for val in y_train:
    if val == 1:
        color_lst.append('b')
    else:
        color_lst.append('r')
color_lst

['b', 'b', 'b', 'b', 'r', 'r', 'r']

In [11]:
label = []
for val in y_train:
    if val == 1:
        label.append('H')
    else:
        label.append('NH')
label

['H', 'H', 'H', 'H', 'NH', 'NH', 'NH']

In [12]:
from sklearn import svm
svm_classifier = svm.SVC(kernel='linear', C=10)
svm_classifier.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [13]:
svm_classifier.n_support_

array([2, 1], dtype=int32)

In [15]:
svm_classifier.support_vectors_

array([[2.155826, 6.222343],
       [3.273418, 3.520687],
       [3.156983, 5.467077]])