In [1]:
import pandas as pd

df = pd.read_csv('SVM_Dataset1.csv', index_col = 0)

In [2]:
df

X1        X2  y
0  2.947814  6.626878  1
1  2.530388  7.785050  1
2  3.566991  5.651046  1
3  3.156983  5.467077  1
4  2.582346  4.457777 -1
5  2.155826  6.222343 -1
6  3.273418  3.520687 -1

In [6]:
import numpy as np
X1 = df['X1']
X2 = df['X2']
X_train = np.array(list(zip(X1,X2)))
X_train

array([[2.947814, 6.626878],
       [2.530388, 7.78505 ],
       [3.566991, 5.651046],
       [3.156983, 5.467077],
       [2.582346, 4.457777],
       [2.155826, 6.222343],
       [3.273418, 3.520687]])

In [8]:
y_train = df['y'].values

print(y_train)

[ 1  1  1  1 -1 -1 -1]


In [9]:
color_lst = []
for val in y_train:
    if val == 1:
        color_lst.append('b')
    else:
        color_lst.append('r')
color_lst

['b', 'b', 'b', 'b', 'r', 'r', 'r']

In [11]:
label = []
for val in y_train:
    if val == 1:
        label.append('H')
    else:
        label.append('NH')
label

['H', 'H', 'H', 'H', 'NH', 'NH', 'NH']

In [12]:
from sklearn import svm
svm_classifier = svm.SVC(kernel='linear', C=10)
svm_classifier.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [13]:
svm_classifier.n_support_

array([2, 1], dtype=int32)

In [15]:
svm_classifier.support_vectors_

array([[2.155826, 6.222343],
       [3.273418, 3.520687],
       [3.156983, 5.467077]])

In [16]:
weight = svm_classifier.coef_
intercept = svm_classifier.intercept_
print(weight)
print(intercept)

[[2.90336685 1.20121959]]
[-14.73321143]


In [19]:
svm_classifier.predict([[3,4]])

array([-1])

In [31]:
import matplotlib.pyplot as plt
df2=pd.read_csv('SVM_Dataset2.csv')
df2


x1  x2  y
0    7.0  20 -1
1    8.0  12 -1
2    9.0  19 -1
3   10.0  17 -1
4   11.0  15 -1
5   13.0  14 -1
6   14.0  12 -1
7   15.0  14 -1
8   15.0  17 -1
9   16.0  16 -1
10   4.0  15  1
11   5.5  12  1
12   7.0  10  1
13   8.0  10  1
14   9.0   9  1
15  10.0   8  1
16  11.0   5  1
17  12.0   7  1
18  12.0   9  1
19  13.0  10  1

In [37]:
X1=df2['x1']
X2=df2['x2']
X_train = np.array(list(zip(X1, X2)))
X_train

array([[ 7. , 20. ],
       [ 8. , 12. ],
       [ 9. , 19. ],
       [10. , 17. ],
       [11. , 15. ],
       [13. , 14. ],
       [14. , 12. ],
       [15. , 14. ],
       [15. , 17. ],
       [16. , 16. ],
       [ 4. , 15. ],
       [ 5.5, 12. ],
       [ 7. , 10. ],
       [ 8. , 10. ],
       [ 9. ,  9. ],
       [10. ,  8. ],
       [11. ,  5. ],
       [12. ,  7. ],
       [12. ,  9. ],
       [13. , 10. ]])

In [36]:
y_train = df2['y'].values
y_train

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1])

In [35]:
colors_lst = []

for k in y_train:
    if k == 1:
        colors_lst.append('b')
    else:
        colors_lst.append('r')
colors_lst

['r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b']

In [38]:
label = []

for k in y_train:
    if k == 1:
        label.append('H')
    else:
        label.append('NH')
label

['NH',
 'NH',
 'NH',
 'NH',
 'NH',
 'NH',
 'NH',
 'NH',
 'NH',
 'NH',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H',
 'H']

In [39]:
svm_classifier = svm.SVC(kernel='poly', C=1, degree=2)
svm_classifier.fit(X_train, y_train)

/anaconda2/lib/python2.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)