In [1]:
#2d array

#find min for each column

#subtract min from each val in col

#divide results of this operation on min and max val


In [2]:
import numpy as np
import pandas as pd

In [3]:
def matrix_stand():
    x = np.array([[1000, 2], [1500, 3]])

    for col in x:
        min = np.min(x, axis = 0)
        max = np.max(x, axis=0)
        range = max - min
        num = x - min
        solution = num//range
    return solution
        
    
    
    

In [4]:
print(matrix_stand())

[[0 0]
 [1 1]]


In [8]:
from sklearn import preprocessing

X_train = np.array([[1000, 2], [1500, 3]])

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

[[0. 0.]
 [1. 1.]]


/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
#find avg of each column and subtract from sum of all elements
#divide avg/std dev

def matrix_std_dev(x):
    for col in x:
        avg = np.mean(x,axis =0)
        std_dev = np.std(x, axis=0)
    return(x-avg)//std_dev

print(matrix_std_dev(X_train))

[[-1. -1.]
 [ 1.  1.]]


In [6]:
import sklearn
print(sklearn.__version__)

0.20.1
